# Generated by Django 6.0.6 on 2026-06-21 16:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_leaderinvitecode_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=accounts.models.generate_admin_code, max_length=12, unique=True)),
                ('role_type', models.CharField(choices=[('LEADER', 'Scout Leader'), ('ARIF', 'Arif')], default='ARIF', max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LeaderInviteCode',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LEADER', 'Scout Leader'), ('ARIF', 'Arif (Small Group Leader)'), ('SCOUT', 'Scout Member'), ('ADMIN', 'Admin')], default='SCOUT', max_length=20),
        ),
    ]
