# Generated by Django 5.2.15 on 2026-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bio_user_phone_number_user_profile_picture'),
        ('camp', '0004_scoutgroup_avatar_preset_scoutgroup_banner_preset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moderated_groups',
            field=models.ManyToManyField(blank=True, related_name='moderators', to='camp.scoutgroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='unlimited_instants',
            field=models.BooleanField(default=False),
        ),
    ]
