# Generated by Django 5.2.16 on 2026-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_moderated_groups_user_unlimited_instants'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvitecode',
            name='gender',
            field=models.CharField(choices=[('BOY', 'Boy Scout'), ('GIRL', 'Girl Scout')], default='BOY', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('BOY', 'Boy Scout'), ('GIRL', 'Girl Scout')], default='BOY', max_length=10),
        ),
    ]
