# Generated by Django 5.2.16 on 2026-07-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_admininvitecode_gender_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininvitecode',
            name='role_type',
            field=models.CharField(choices=[('LEADER', 'Scout Leader'), ('AMIID', 'Amiid / 3amida')], default='AMIID', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LEADER', 'Scout Leader'), ('AMIID', 'Amiid / 3amida (Small Group Leader)'), ('SCOUT', 'Scout Member'), ('ADMIN', 'Admin')], default='SCOUT', max_length=20),
        ),
    ]
