# Generated by Django 5.2.16 on 2026-07-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_admininvitecode_role_type_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininvitecode',
            name='role_type',
            field=models.CharField(choices=[('LEADER', 'Scout Leader'), ('AMIID', 'Amiid / Amiida')], default='AMIID', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LEADER', 'Scout Leader'), ('AMIID', 'Amiid / Amiida (Small Group Leader)'), ('SCOUT', 'Scout Member'), ('ADMIN', 'Admin')], default='SCOUT', max_length=20),
        ),
    ]
