# Generated by Django 6.0.6 on 2026-06-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutprofile',
            name='group_role',
            field=models.CharField(choices=[('SECOND_LEADER', 'مساعد عريف'), ('WRITER', 'كاتب/مدون'), ('CHEF', 'طباخ'), ('SINGER', 'منشد'), ('MEMBER', 'عضو')], default='MEMBER', max_length=20),
        ),
    ]
