# Generated by Django 6.0.6 on 2026-06-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_scoutprofile_group_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutgroup',
            name='avatar_preset',
            field=models.CharField(default='tent', max_length=50),
        ),
        migrations.AddField(
            model_name='scoutgroup',
            name='banner_preset',
            field=models.CharField(default='forest', max_length=50),
        ),
        migrations.AddField(
            model_name='scoutgroup',
            name='theme_color',
            field=models.CharField(default='blue', max_length=50),
        ),
    ]
