# Generated by Django 5.2.15 on 2026-07-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_game_gamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='instantane_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_daily_instantane',
            field=models.BooleanField(default=False, help_text='If checked, this game automatically calculates daily Instantane reaction winners.'),
        ),
    ]
