# Generated by Django 5.2.15 on 2026-07-03 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_wheelspin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g. Flame, Tent, Compass)', max_length=50)),
                ('icon_color_class', models.CharField(help_text='CSS class for color (e.g. badge-fire, badge-knot)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='camp.badge')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='camp.scoutgroup')),
            ],
            options={
                'unique_together': {('group', 'badge')},
            },
        ),
    ]
