# Generated by Django 5.2.16 on 2026-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0008_badge_earnedbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_wheel_spinner',
            field=models.BooleanField(default=False, help_text='If checked, this game automatically tallies points won from the Wheel Spin.'),
        ),
    ]
