# Generated by Django 5.2.16 on 2026-07-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0009_game_is_wheel_spinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='instantane_start_date',
        ),
        migrations.AddField(
            model_name='game',
            name='active_since',
            field=models.DateTimeField(blank=True, help_text='Exact time this game was enabled.', null=True),
        ),
    ]
