# Generated by Django 5.2.16 on 2026-07-16 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0010_remove_game_instantane_start_date_game_active_since'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gender',
            field=models.CharField(choices=[('BOTH', 'Both'), ('BOY', 'Boy Scouts'), ('GIRL', 'Girl Scouts')], default='BOTH', help_text='Which group(s) this game applies to', max_length=4),
        ),
        migrations.CreateModel(
            name='PianoScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piano_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
